steps:
- name: 'gcr.io/kaniko-project/executor:perf-latest'
  args:
  - --build-arg=NUM=${_COUNT}
  - --no-push
  - --snapshotMode=redo
  env:
  - 'BENCHMARK_FILE=gs://tejal-test/redo_gcb/benchmark_file_${_COUNT}'
  timeout: 2400s
timeout: 2400s
substitutions:
  _COUNT: "10000" # default value